site_name: Suuchi
repo_url: https://github.com/ashwanthkumar/suuchi/
site_description: Toolkit to build data systems
theme: flatly

pages:
- 'Introduction': 'index.md'
- 'Quick Start': 'quick-start.md'
- Internals:
    - 'Aggregation': 'internals/aggregation.md'
    - 'Partitioner': 'internals/partitioner.md'
    - 'Replication': 'internals/replication.md'
    - 'Router': 'internals/router.md'
- Recipes:
    - 'Distributed In Memory Database': 'recipes/inmemorydb.md'
    - 'Distributed RocksDB Database': 'recipes/rocksdb.md'
    - 'Distributed KVClient': 'recipes/kvclient.md'
- Developer:
    - 'Release Workflow': 'developer/workflow.md'
